# Generated by Django 5.2.4 on 2026-03-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("lieu", models.CharField(max_length=150)),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[("CDI", "CDI"), ("CDD", "CDD"), ("STAGE", "Stage")],
                        max_length=20,
                    ),
                ),
                ("nombre_postes", models.PositiveIntegerField(default=1)),
                ("date_limite", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("PUBLIE", "Publié"),
                            ("EXPIRE", "Expiré"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre",
                "verbose_name_plural": "Offres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileRecherche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.offre"
                    ),
                ),
            ],
        ),
    ]
