# Generated by Django 5.2.4 on 2026-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_actualite_translation_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualite",
            name="contenu_en",
            field=models.TextField(
                help_text="Texte complet de l’actualité (retours à la ligne conservés).",
                null=True,
                verbose_name="Contenu",
            ),
        ),
        migrations.AlterField(
            model_name="actualite",
            name="contenu_fr",
            field=models.TextField(
                help_text="Texte complet de l’actualité (retours à la ligne conservés).",
                null=True,
                verbose_name="Contenu",
            ),
        ),
        migrations.AlterField(
            model_name="actualite",
            name="resume_en",
            field=models.TextField(
                help_text="Texte court affiché dans la liste des actualités.",
                null=True,
                verbose_name="Résumé",
            ),
        ),
        migrations.AlterField(
            model_name="actualite",
            name="resume_fr",
            field=models.TextField(
                help_text="Texte court affiché dans la liste des actualités.",
                null=True,
                verbose_name="Résumé",
            ),
        ),
        migrations.AlterField(
            model_name="actualite",
            name="titre_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="actualite",
            name="titre_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Titre"),
        ),
    ]
