# Generated by Django 5.2.4 on 2026-05-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_actualite_image"),
        ("app", "0008_alter_actualite_contenu_en_and_more"),
    ]

    operations = []
