# Generated by Django 5.2.4 on 2026-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_merge_20260520_1013"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="galerie/")),
                ("description", models.TextField()),
                ("est_active", models.BooleanField(default=True)),
            ],
        ),
    ]
