# Generated by Django 5.2.4 on 2026-07-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_galerie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galerie",
            options={"verbose_name": "Galerie", "verbose_name_plural": "Galerie"},
        ),
        migrations.AlterField(
            model_name="galerie",
            name="image",
            field=models.ImageField(upload_to="twiga_power/galerie/"),
        ),
    ]
