# Generated by Django 5.2.4 on 2026-07-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_galerie_options_alter_galerie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galerie",
            name="image",
            field=models.ImageField(upload_to="twigapower/galerie/"),
        ),
    ]
